
spring.datasource.url= jdbc:postgresql://localhost:5432/marketplace
spring.datasource.username= Owner
spring.datasource.password= 123456

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update