
spring.datasource.url= jdbc:postgresql://localhost:5432/marketplace
spring.datasource.username= Owner
spring.datasource.password= 123456

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update

# ????????? ???????? ??????
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true


#????????? Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#  ???? ??? ????? ?????? ??? ?????, ??????????? ? Liquibase.
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml


file.upload.dir=C:/uploads
# ????????? cleanup ??? ????????? ?????? (?????? ?????? ? ?????????)
spring.servlet.multipart.resolve-lazily=true

# ????????? security ??? endpoints ???????????? (??? ????????????)
management.endpoints.web.exposure.include=*
# ????????? ??????????? ??????????? ????????
spring.web.resources.cache.cachecontrol.max-age=0
spring.web.resources.cache.cachecontrol.no-cache=true

logging.level.org.springframework.web=DEBUG
logging.level.com.yourpackage=DEBUG